create table employee(
    id serial primary key,
    first_name varchar not null,
    last_name varchar not null,
    serial_number varchar not null unique,
    birthday date,
    pic_url text,
    sex varchar not null,
    location varchar not null,
    pro_email varchar not null,
    ps_email varchar,
    function varchar,
    social_category varchar not null,
    dependent_children int not null ,
    cnaps_serial_number varchar not null,
    hire_date date not null,
    resignation_date date,
    identity_card_id varchar not null,
    identity_card_del_place varchar not null ,
    identity_card_del_date date not null
)